### ISSUE TITLE
Importation de données depuis Eclipse

### ISSUE THREAD

**Issue by ColinMourard** [ColinMourard/ProjetGGTS#1]
Soit on trouve comment faire (on peut demander aux fantastiques)
Sinon avec les lignes de commande (cf. Bastien)

**Comment by Silhouan** [comment]
J'ai réussi à mettre le projet dans le dépôt. Dès que tout le monde aura testé la méthode d'Anthony et aura vérifié qu'il peut faire des pull, commit et push avec GGTS, on pourra fermer l'issue.

**Comment by apagliai** [comment]
Pour ceux qui n'arrivent pas à faire "Commit and Push" d'un coup : 
Team > Commit, et après dans le menu qui apparait c'est ici que vous pouvez choisir de ne faire qu'un "Commit" simple ou de faire "Commit and push" d'un coup !
