### ISSUE TITLE
Format des délais

### ISSUE THREAD

**Issue by Silhouan** [ColinMourard/ProjetGGTS#3]
Postez ici vos suggestions pour le format des délais !

**Comment by Silhouan** [comment]
Pour le moment j'ai en tête trois propositions qui avaient été faites : 
1 - On utilise un String qui est créé/parsé dans le contrôleur pour que l'utilisateur manipule des int;
2 - On utilise un int directement;
3 - On utilise carrément la classe Date ou Calendar

**Comment by mcaillet** [comment]
Yo j'ai réfléchi à ce sujet.
Le problème de la solution 2 c'est qu'il faudrait à priori rentré 3 entiers pour le jour (jj/mm/aaaa) et deux entiers pour les heures (genre 15h47), au bout d'un moment ça fait beaucoup de variables, donc si on opte pour cette solution faudra pas se mélanger les cagettes de fruits avec. Sinon je vois pas d'autres problèmes mais je suis sûr qu'il y en a.

Pour la troisième solution, utiliser un Calendar ce serait pas mal. En gros je vois ça comme ça:
-l'utilisateur rentre une date du genre (jour/mois) et une heure (heure/minute)
-Ensuite dans le controller on met à jour un calendar (qui serait attributaire du questionnaire) qu'on     update avec la méthode set(int year,int month,int day,int hour,int minuts) où les quatres derniers entiers sont ceux donnés par l'utilisateur.
Le lecteur averti aura remarqué qu'il ne nous manque que l'année. Plutôt que de mettre 2015 comme des grosses brutes il faudrait plutôt trouver un moyen de prendre l'année en cours du genre:
                Date d = new Date(); //prend la date d'aujourd'hui
        System.out.println(d.getYear()+1900); //Dans la javadoc y disent que getYear() a été remplacée par Calendar.get(Calendar.YEAR) - 1900, cependant faut créer un calendar avec un constructeur qui a besoin de l'année en cours (tu comprends le dilemne tu vois)
J'ai testé ce ptit bout de code dans eclipse et ça marche du tonnerre! 
-Une fois que tu as ton calendar crée par ton controller on le compare au calendar de la classe du domaine pour savoir si on a dépassé la date de péremption du dit questionnaire.

Je sais mon commit est un peu long, les explications ne sont pas très claires par moment, de toute façon on en parlera lundi matin.

**Comment by apagliai** [comment]
Perso je suis d'accord avec Maxime.
Pour le projet Traffic Aérien avec Colin on avait notre heure au format [h,min,s] avec un tableau de 3 entiers et ça faisait beaucoup de variables en effet. Après ça marchait très bien !

**Comment by ColinMourard** [comment]
En plus, on a déjà les méthodes pour convertir les ms de la machine (genre currentTimeMillis) en [h,m,s]. Donc aussi d'avis du HAUT Savoyard

**Comment by Pierre14** [comment]
D'accord pour utiliser la classe Calendar : je m'en suis servi sur le projet "aéroport" et elle est plutôt pratique !
En revanche, il me semble que la plupart des méthodes de la classe Date sont dépréciées (par rapport à ce que tu proposais Maxime) donc je suggère de l'éviter par principe...

**Comment by mcaillet** [comment]
Elles ont juste été remplacées par de nouvelles méthodes mais elles marchent toujours!

**Comment by Silhouan** [comment]
Dans ce j'avais compris sur internet, Calendar a été créée car Date commençait à sérieusement être obsolète, et qu'elle n'était toujours là que pour des raisons de compatibilité...
Si quelqu'un a déjà commencé à s'en occuper, l'idéal est qu'il se mette en _assignee_, comme ça on sait directement qui contacter si jamais on a une suggestion à faire.
Si jamais personne veut le faire, je veux bien m'en charger.

**Comment by Pierre14** [comment]
Juste pour être sûr d'avoir bien compris : on crée un controller spécifique pour gérer ces histoires de dates, c'est ça ?
