### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by mcaillet** [ColinMourard/ProjetGGTS#4]
Bonjour mes chatons!
Je créais une issue pour l'authentification parce que faudra bien se pencher dessus un moment ou à un autre!
J'ai eu une idée de génie (que j'ai pas encore testé) en relisant le cours sur les 3 R.
Dans le controller qui gère l'authentification on pourrait créer une méthode qui utilise une instance de Compte et qui recherche dans la base de données si le compte existe avec un findByAttribute() !
Nooooooon ne me remerciez pas! C'est un plaisir que de mettre mon génie à votre service mes coupaings!

**Comment by Silhouan** [comment]
Oui effectivement, c'est un des avantages d'avoir une classe commune aux trois compte, mais il y a un problème... Je crois que Grails aime pas trop le belongsTo avec plusieurs possibilités (je sais pas si tu as essayé de faire un compte, mais de mon coté ça me renvoie une erreur à chaque fois...). Du coup je me demande si il vaudrait pas mieux, avant de faire l'authentification, d'essayer de faire une architecture des comptes un peu plus performante. Peut-être faire une seule classe avec un attribut type qui défini l'accès aux autres attributs... Reste à voir si on peut faire des if dans les contraintes.

**Comment by mcaillet** [comment]
Chef oui chef! =P
J'ai trifouillé les méandres obscurs de l'Internet et j'ai trouvé un forum ou un mec explique et donne classes et pages gsp afin de faire de l'authentification. Je pense que je vais essayer de m'en inspirer.
http://www.ibm.com/developerworks/java/library/j-grails04289/index.html (je me met le site sous le coude)

**Comment by Silhouan** [comment]
Effectivement ton site à l'air pas mal du tout !
Ce que j'avais en tête ressemblait un peu à son histoire de rôle, mais du coup autant prendre la solution qu'il propose ^^ ! Tu t'en occupe ? Je voudrais faire encore quelques tests avec les histoires de list/question/reponses etc.

**Comment by mcaillet** [comment]
J'ai essayé de faire marcher son truc dans mais quand je teste le contoller authenticate y m'envoie une page erreur (alors que dans le boot strap j'ai créer un compte admin avec comme login et comme password le mot admin).
Du coup je comprend pas. Autrement dit no comprendo senor. Et j'ai pas envie de me prendre la tête dessus dans ce qu'il me reste de vacances du coup je verrais ça lundi en détail (dussé-je y passer le cours de socio)

**Comment by mcaillet** [comment]
J'ai réglé le problème Sir!
En fait dans le UserController quand l'authentification est bonne tu es redirigé vers un controller entry.
Comme j'ai la flemme de le trouver sur le site j'ai changé la redirection pour rediriger l'utilisateur vers user/index.
Du coup faudra que je vois lundi comment faire pour faire un truc propre du genre le mec envoie une requête et BAM! il est envoyé sur l'authentification!
Faudrait que je rajoute un bouton logout une fois que t'es connecté pour pouvoir te déco!

**Comment by Silhouan** [comment]
C'est une bonne nouvelle ça.
Pense à pusher ce que tu fais de temps en temps, ça m'intéresserait de voir ce que ça donne !

**Comment by Silhouan** [comment]
D'ailleurs j'ai trouvé comment faire des if dans les constraints : il faut utiliser un [validator](http://grails.github.io/grails-doc/latest/ref/Constraints/validator.html)

**Comment by Silhouan** [comment]
J'ai mis à jour le système de compte ; il n'y a plus qu'une seule classe désormais, avec une variable type.
