### ISSUE TITLE
Questionnaire

### ISSUE THREAD

**Issue by mcaillet** [ColinMourard/ProjetGGTS#5]
Copie du mail de Bastien:
On va commencer par se concentrer juste sur la partie qui concerne la création des questionnaires, pour prendre nos marques et nous assurer que c'est une façon de répartir le travail qui marche bien. Les pages concernées sont :
    - Création du questionnaire (structure globale + questionnaire simple);
    - Création du questionnaire détaillé;
    - Affichage de la liste des questions avec possibilité de modifications;
    - Ajout (modification) d'une question.

Le travail est réparti sur trois niveaux :
    1) L'affichage : Marine, Colin et Anthony(?)
    Gestion des pages GSP. C'est vous qui avez le travail le plus urgent, puisque c'est vous qui précisez les actions à créer (leur nom, ce qu'elles reçoivent en paramètres et ce qu'elles revoient à leur page GSP) et dans quel Controller il faut les mettre.
    2) Les Controllers intermédiaires : Pierre, Maxime et moi-même
    Ce sont les Controllers qui traduisent les évènements (reçus de l'affichage) en une série d'actions éxecutées sur la base de données. Il faut notamment vérifier la validité des différentes actions demandées etc.
    3) Les Controllers de la DB : dans un second temps
    S'assurer que ceux du point 2) puissent faire ce qu'ils veulent sur les éléments de la DB.

Points soulevés mais qui seront gérés plus tard :
    - Création d'une DB permanente, qui conserve les modifications quand le serveur est redémarré.
    - Authentification : comment savoir lequel des utilisateurs connecté demande telle ou telle action?

**Comment by mcaillet** [comment]
J'ai aussi ajouté une branche Questionnaire dans laquelle on fera toutes nos avancées.
Je pense qu'une fois que l'on en aura terminé avec les questionnaires on n'aura plus qu'à l'adapter pour les réponses (je pense qu'il n'y aura que quelques détails qui changeront)

**Comment by Silhouan** [comment]
Euh... En fait y a un petit soucis. La nouvelle branche est basée sur la branche **authentification**, qui ne possède pas le nouveau système de questionnaires. Du coup on peut soit : 
- détruire la branche et en créer une nouvelle à partir de **master**
- merger celle déjà existante avec **master**.

Personnellement je suis plutôt en faveur de la première solution, et ensuite on ajoute le nouveau système de Compte à toutes les branches qui ne l'ont pas. Ça évitera que le système d'authentification - qui si j'ai bien compris n'est pas encore fini - se balade dans les différentes branches.

**Comment by Silhouan** [comment]
C'est bon, **master** a le nouveau système de compte. Du coup les deux solutions ci-dessus donnent le même résultat.
@mcaillet : Comme c'est toi qui a créé la branche, je laisse faire, avec la méthode que tu préfères. Pense que si tu détruis la branche, il faut le faire sur GitHub _et_ sur ton ordi, car une branche détruite sur une plateforme n'est pas détruite sur les autres (c'est une sécurité de git).

**Comment by mcaillet** [comment]
Ok je m'en occuperais demain (si j'oublie pas ou si j'ai pas la flemme)
