### ISSUE TITLE
Anonymat total ou non ?

### ISSUE THREAD

**Issue by Silhouan** [ColinMourard/ProjetGGTS#6]
Juste une petite issue pour faire un sondage.
Pour le moment, telles que les classes sont faites, il n'y a aucun moyen d'associer un élève aux réponses qu'il a données. La question est  : 
Est-ce qu'on laisse ça comme ça, ou bien on permet à l'élève de revoir plus tard ce qu'il a répondu ?

**Comment by mcaillet** [comment]
Non on laisse comme ça.
Il assume ce qu'il pense!

**Comment by Silhouan** [comment]
Y en a-t-il qui ne sont pas d'accord ? Sinon je ferme l'issue.

**Comment by ColinMourard** [comment]
Salut les jeunes, 
Je pense que le principe de l'anonymat c'est de pas pouvoir remonter à l'élève. Si on permet (au bon vouloir de l'admin) l'accès au nom c'est plus anonyme. Donc pour moi faut pas associer élève et questionnaire.

**Comment by Pierre14** [comment]
Je suis aussi pour laisser ça comme ça.

**Comment by Silhouan** [comment]
Bon comme ça on est au moins 4 du même avis ^^ Du coup on laisse ça comme ça _a priori_, à moins qu'on trouve une excellente de faire autrement plus tard.
Je ferme l'issue.

**Comment by mcaillet** [comment]
une excellente quoi? (oui je suis chiant =P #DéjàVu)

**Comment by Silhouan** [comment]
raison...
Satisfait ? (j'ai été pris à mon propre jeu :sob: )
